spring.application.name=Backend

#DataBase Configuration
spring.datasource.url=jdbc:mysql://localhost:33061/TechBlogApp?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#JWT
techblog.app.jwtSecret = ======================JwtSecret===========================
techblog.app.jwtExpirationMs = 900 000
techblog.app.jwtCookieName= techblog-jwt
techblog.app.jwtRefreshCookieName= techblog-jwt-refresh
techblog.app.jwtRefreshExpirationMs = 604 800 000

